# Generated by Django 5.0.3 on 2024-03-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0002_circulation_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulation',
            name='returned_at',
            field=models.DateTimeField(blank=True, help_text='Datetime at which the book was returned by the member', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, help_text='Datetime at which the reservation was fulfilled', null=True),
        ),
    ]
